name: Generate Datas

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MarinaSDiniz
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env: # Environment variables should not be under 'with'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Runs a set of commands using the runner's shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
